import Navbar from '@/components/navbar/Navbar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.2/css/all.css" />
      </head>
      <body>
        <div className="navbar">
          <Navbar />
        </div>

        <div className="app-content">
          {children}
        </div>
      </body>
    </html>
  )
}
