import React from 'react'

export const metadata = {
    title: 'About Page',
    description: 'Generated by create next app',
}

export default function AboutLayout({ children }) {
    return (
        <>
            <div><p>This is a nested layout in about page</p></div>
            <main>
                {children}
            </main>
        </>
    );
}
